### PR TITLE
First Class Function Closures

### PR DESCRIPTION
**Pull request by DuncanUszkay1**
The latest iteration in Closure PRs.

- In this PR, the concept of a first class function was introduced into the language: https://github.com/AssemblyScript/assemblyscript/pull/1384
- We've rebased onto master, and now we're going to rebuild closures onto this new first class function concept.
- Closing https://github.com/DuncanUszkay1/assemblyscript/pull/11, but we'll be using it as a reference to reimplement here

cc @torch2424 

- [x] I've read the contributing guidelines

### CODE REVIEW

**Comment by torch2424** [comment]
@DuncanUszkay1 Thank you for doing this! :smile: 

So should we start re-implementing things on this PR/Branch? :smile:

**Comment by DuncanUszkay1** [comment]
>So should we start re-implementing things on this PR/Branch?

Let's make PRs onto this branch

**Comment by torch2424** [comment]
@DuncanUszkay1 Sounds good! Currently been a bit busy with Fastly stuff, but I can do that after :smile: :+1:

**Comment by DuncanUszkay1** [comment]
Closing out some old PRs

**Pull request closed without merging**
